services:
  postgres:
    image: postgres:17-alpine
    environment:
      # database 'cityracing' will be automatically created
      # (if not set uses POSTGRES_USER as db name)
      - POSTGRES_USER=cityracing
      - POSTGRES_PASSWORD=development
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432 # host:container
  
  oidc:
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
      - 8081:8080 # host:container
    environment:
      - USERS_CONFIGURATION_PATH=/config/users.json
      - CLIENTS_CONFIGURATION_PATH=/config/clients.json
      - SERVER_OPTIONS_PATH=/config/server.json
    volumes:
      - ./config/oidc:/config:ro
